"""Fail if generated artifacts or client exports are tracked in git.

Issued audit packages are immutable, hash-registered records — a casually
re-committed copy in source control both churns the history and undermines
that posture, and client exports must never land in the repository at all.
Run locally or in CI:

    python scripts/check_no_generated_artifacts.py
"""
from __future__ import annotations

import fnmatch
import subprocess
import sys

FORBIDDEN_PATTERNS = [
    "examples/output/*",          # regenerated by examples/build_example_case.py
    "dist/*",                     # standalone build output
    "*.pyc",
    "*__pycache__*",
    ".pytest_cache/*",
    "node_modules/*",
    "*.egg-info/*",
    "pkg_*.xlsx",                 # issued audit packages (immutable, stored out of band)
    "export_*.json",              # canonical case exports (client data)
    "*audit.jsonl",               # append-only store audit logs
    "*.xlsx",                     # no workbook belongs in source control
]


def main() -> int:
    tracked = subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
    offenders: list[tuple[str, str]] = []
    for path in tracked:
        for pattern in FORBIDDEN_PATTERNS:
            if fnmatch.fnmatch(path, pattern):
                offenders.append((path, pattern))
                break
    if offenders:
        print("Generated artifacts or client exports are tracked in git:")
        for path, pattern in offenders:
            print(f"  {path}   (matched {pattern!r})")
        print("\nRemove them (git rm --cached) and rely on .gitignore; issued")
        print("audit packages live outside source control by design.")
        return 1
    print(f"OK — {len(tracked)} tracked files, no generated artifacts or client exports.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
