"""Immutable, tax-year-versioned ruleset registry.

Rules live in JSON data files (see data/), generated by scripts/build_rulesets.py,
never in application code or prompts. A calculation request must pin exact
ruleset versions; missing or cross-year rulesets are rejected.
"""
from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path
from types import MappingProxyType
from typing import Any

from ..money import d
from ..schemas import FilingStatus, content_hash

_DATA_DIR = Path(__file__).resolve().parent / "data"


class RulesetError(Exception):
    pass


class Ruleset:
    """Read-only view over one released ruleset file."""

    def __init__(self, raw: dict[str, Any]):
        self._raw = raw
        self.ruleset_id: str = raw["version"]
        self.jurisdiction: str = raw["jurisdiction"]
        self.tax_year: int = raw["tax_year"]
        self.status: str = raw["status"]  # "enacted" | "provisional"
        self.source_references: list[str] = list(raw["source_references"])
        self.provisional_policy: dict[str, Any] | None = raw.get("provisional_policy")
        self._params = MappingProxyType(raw["parameters"])
        self.content_hash = content_hash(raw)

    @property
    def is_provisional(self) -> bool:
        return self.status == "provisional"

    def param_id(self, name: str, filing_status: FilingStatus | None = None) -> str:
        suffix = f".{filing_status.value}" if filing_status else ""
        return f"{self.ruleset_id}:{name}{suffix}"

    def amount(self, name: str, filing_status: FilingStatus | None = None) -> Decimal:
        """Fetch a dollar-amount parameter as Decimal."""
        raw = self._params[name]
        if filing_status is not None:
            raw = raw[filing_status.value]
        return d(raw)

    def rate(self, name: str, key: str | None = None) -> Decimal:
        raw = self._params[name]
        if key is not None:
            raw = raw[key]
        return d(raw)

    def brackets(self, filing_status: FilingStatus) -> list[tuple[Decimal | None, Decimal]]:
        return [
            (None if ub is None else d(ub), d(rate))
            for ub, rate in self._params["ordinary_brackets"][filing_status.value]
        ]

    def manifest(self) -> dict[str, Any]:
        return {
            "ruleset_id": self.ruleset_id,
            "jurisdiction": self.jurisdiction,
            "tax_year": self.tax_year,
            "status": self.status,
            "content_hash": self.content_hash,
            "source_references": self.source_references,
            "provisional_policy": self.provisional_policy,
        }

    def raw_parameters(self) -> dict[str, Any]:
        return json.loads(json.dumps(dict(self._params)))


class RulesetRegistry:
    """Loads released rulesets from disk; refuses to serve unknown versions."""

    def __init__(self, data_dir: Path = _DATA_DIR):
        self._by_id: dict[str, Ruleset] = {}
        for path in sorted(data_dir.glob("*.json")):
            rs = Ruleset(json.loads(path.read_text()))
            self._by_id[rs.ruleset_id] = rs

    def get(self, ruleset_id: str) -> Ruleset:
        if ruleset_id not in self._by_id:
            raise RulesetError(f"unknown ruleset version: {ruleset_id!r}")
        return self._by_id[ruleset_id]

    def latest_for_year(self, tax_year: int, jurisdiction: str = "US-FEDERAL") -> Ruleset:
        candidates = [
            rs for rs in self._by_id.values()
            if rs.tax_year == tax_year and rs.jurisdiction == jurisdiction
        ]
        if not candidates:
            raise RulesetError(
                f"no ruleset released for {jurisdiction} tax year {tax_year}"
            )
        return sorted(candidates, key=lambda rs: rs.ruleset_id)[-1]

    def pin_for_years(self, years: list[int]) -> dict[int, str]:
        """Resolve one pinned ruleset id per requested year."""
        return {y: self.latest_for_year(y).ruleset_id for y in years}

    def validate_pins(self, pins: dict[int, str]) -> None:
        """Reject missing pins and year/ruleset mismatches (no cross-year mixing)."""
        for year, ruleset_id in pins.items():
            rs = self.get(ruleset_id)
            if rs.tax_year != year:
                raise RulesetError(
                    f"ruleset {ruleset_id} is for tax year {rs.tax_year}, "
                    f"cannot be pinned to {year} — parameters from different tax "
                    "years must never be mixed"
                )


DEFAULT_REGISTRY = RulesetRegistry()
